### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KayNguyen97** [dante4rt/Berachain-Faucet-Taker#1]
![bera](https://github.com/dante4rt/Berachain-Faucet-Taker/assets/126054099/7437e4b0-135f-4552-8b17-413cb6f4ae34)
please help

**Comment by dante4rt** [comment]
> ![bera](https://private-user-images.githubusercontent.com/126054099/309437640-7437e4b0-135f-4552-8b17-413cb6f4ae34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzODM2MjcsIm5iZiI6MTcwOTM4MzMyNywicGF0aCI6Ii8xMjYwNTQwOTkvMzA5NDM3NjQwLTc0MzdlNGIwLTEzNWYtNDU1Mi04YjE3LTQxM2NiNmY0YWUzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQxMjQyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGI1YmVmMGJiN2JjY2RhZGM3MzkwNzE5MGYzMDlmNDZlMjIzZDczZjJmZjcxMTliMGE0ZDM3MTZkOTEyYTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X7YDIDk-pp6UT6uvkiAE5PtYRQjeiKzoYSUiZQ5VXqU) please help

Thanks for bringing this to our attention. Indeed, there has been an update on the website which caused the crawler to malfunction. I'll make sure to update it as soon as possible. Additionally, I'm open to any contributions or updates via pull requests. Feel free to submit one if you're willing to help out. Thanks again for your understanding.
